### ISSUE TITLE
Fantastic concept

### ISSUE THREAD

**Issue by jgwinner** [nickcoutsos/keyboard-presentation#1]
If I understand the presentation correctly, this is something that could be made from laser cut acrylic, instead of 3D printing?

Do you have the design files anywhere?

Have you made it?

Fantastic concept. Might be easier just to 3D print, but this keyboard would probably be cheaper and would look amazing if made out of acrylic!

== John ==

**Comment by nickcoutsos** [comment]
Hi John, glad you like it! Kudos for going through the slides without any extra context! If you're not familiar, this keyboard is based on the [Dactyl](https://github.com/adereth/dactyl-keyboard/) and you're right that it's meant to be 3D printed.

At the time all of the documentation I'd read indicated that quality 3D prints of the case would cost around $500 which is a big commitment for something I had never even tried. I have access to a 3D printer at work but no matter how I sliced it I'd be looking at something like 40 hours printing time and I wasn't interested in dealing with failed prints (our printer has some layer skipping issues and even smaller prints can be problematic when I'm able to restart quickly while I'm in the office). I had worked with generating laser cutting templates before, so that was my intention here.

I rewrote the original Clojure code in OpenSCAD and designed row and column supports to hold the individual key plates in place, then oriented each piece with the XY plane and projected it to create an SVG template for laser cutting.

![img_20180823_091028787](https://user-images.githubusercontent.com/1165066/50388139-ff291e00-06db-11e9-98c3-caaa90291e6a.jpg)

Here's the end result sitting on my desk at work. You can actually see some 3D printed pieces supporting the thumb cluster, I messed up some matrix transformations that caused the acrylic to snap during assembly, but they were very quick to print. (Also ignore the analog thumbsticks, I hoped they would work well as a mouse and scroll wheel substitute and while it was a fun experiment moving my hand over to an actual mouse is more practical).

I still need to publish the code for this project! I've been working on a new low profile version with a less exaggerated curve and I'm kind of dragging my feet on it but the source is refactored and probably worth releasing on its own now. If you're interested in it I can try to find some time soon to make a repo.

**Comment by jgwinner** [comment]
Nice! Also, your design could allow for a little bit of a modular setup.

I'm familiar with the Dactyl, and I know what you mean - it's a lot of print if I"m not sure I'd like it. For that rate, I'd probably just buy a Kinesis. I've been really happy with their support, and if I upgrade or don't like it, they seem to hold their value well.

I have a big 64 key tester coming, so I can wait a little while, but I keep spending more time than I should looking at these things :)

That amount of cupping looks just about right for me, at a guess.

My problem is that as a C++ programmer, I really like my F keys; I frequently bang on them during debugging and really don't want to have to do a chord to get at them, but maybe I "don't get it". So I was actually messing around with a version that would have F keys on top of the keyboard (like the Kinesis - but not with the dome switches).

The thumb sticks are interesting - I have a couple of old trackballs who's button's aren't working, and have been tempted to rip them apart and see if I can do the same thing.

Thanks so much for the reply, and looking forward to what you've got.

== John ==

**Comment by nickcoutsos** [comment]
Biggest problems with the thumbsticks:

1. I really enjoy kinetic scrolling a la Apple's magic trackpad and I can't replicate that with just a USB HID device. If I integrated a frictionless scroll wheel that might help but there's still:
2. If I want to use these extra inputs to be controlled by my thumbs then the only appropriate place for them is the thumb cluster itself. Stretching past or below the cluster is either a huge strain on the thumb or else force me to move my hand which defeats the purpose. It might work to replace the existing thumb cluster with something that more comfortably fits an analog stick (and maybe a few keys?) but I didn't want to get to crazy with my own ergonomic ideas.

My biggest gripe with the dactyl and other ergonomic designs is that there doesn't seem to be a lot of documentation around the design choices that would help someone else extend it without having to try a bunch of alternatives that others may have already ruled out.

As for F-keys, I think there have been others interested in the same. Fortunately it should be easy enough just to add another row without making significant changes to the code (if the curve causes it to be a tight fit you may have to try smaller keycaps, or filing down some of the edges).

**Comment by nickcoutsos** [comment]
@jgwinner I've just put up a repo for the original/existing OpenSCAD code of the keyboard: [dactyl-flatpacked](https://github.com/nickcoutsos/dactyl-flatpacked)

**Comment by jgwinner** [comment]
Wow! What a great Christmas present :)

Thank you! I'll take a look
